### ISSUE TITLE
Any documentation on how to use this?

### ISSUE THREAD

**Issue by GrandMoff100** [TeamNightSky/StarlaLang#1]
I've searched far and wide and there isn't any documentation on this powerful language.

**Comment by FoxNerdSaysMoo** [comment]
Alas, if only we knew how to utilize the vast power and flexibility that could be unlocked from this language.

**Comment by GrandMoff100** [comment]
'Tis indeed a puzzling problem. So much so i beleieve this deserves an important label.

**Comment by GrandMoff100** [comment]
This issue has become stale. Closing for now.
